myra-invest {

  environment = "local"

  bronze-path = "datasets/bronze/daily_stock_snapshot"

  silver-path ="datasets/silver/stock_snapshot"

  market-provider ="AlphaVantage"

  timezone ="Asia/Kolkata"


}